### ISSUE TITLE
Agregar descripciones de FOSS4G y SOTM

### ISSUE THREAD

**Issue by Zalitoar** [geoinquietos-ar/foss4g-ar#11]

**Comment by Zalitoar** [comment]
Texto propuesto para SOTM:
"State of the Map (SotM) Argentina es la conferencia nacional de [OpenStreetMap](http://www.openstreetmap.org), organizada por las comunidades locales de OSM y Geoinquietos."

**Comment by juanblas09** [comment]
Ya están los textos en la web
